### ISSUE TITLE
Cursor jumps over untyped outer closing brace of nested pair

### ISSUE THREAD

**Issue by jbhannah** [jbhannah/autopairs-code#9]
```
input: {( foo| )} (press ) at |)
output: {( foo )}|
expected: {( foo )|}
```

**Comment by bolderbrooklyn** [comment]
Jumping over newlines in nested pairs worked correctly. The issue was that jumping over a newline requires moving an extra character forward compared to jumping over whitespace on the same line, and that extra step was always being taken even on the same line.
